name: flutter_no_internet_widget
description: A new Flutter widget to show online or offline widget without any
  extra code or dependencies.
version: 1.0.0+1
homepage: https://github.com/HijbullahMahmud/Flutter-No-Internet-Check.git

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  connectivity_plus: ^6.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mocktail: ^1.0.4
  responsive_sizer: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
